package nwts.ru.autoshop.models.network;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import nwts.ru.autoshop.models.DaoSession;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CABINET_MODEL".
*/
public class CabinetModelDao extends AbstractDao<CabinetModel, Long> {

    public static final String TABLENAME = "CABINET_MODEL";

    /**
     * Properties of entity CabinetModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property BalanceID = new Property(1, int.class, "balanceID", false, "BALANCE_ID");
        public final static Property DateOperation = new Property(2, long.class, "dateOperation", false, "DATE_OPERATION");
        public final static Property Balance = new Property(3, double.class, "balance", false, "BALANCE");
        public final static Property CartID = new Property(4, int.class, "cartID", false, "CART_ID");
        public final static Property TovarCount = new Property(5, int.class, "tovarCount", false, "TOVAR_COUNT");
        public final static Property CartSumma = new Property(6, double.class, "cartSumma", false, "CART_SUMMA");
        public final static Property OrderStatus0 = new Property(7, int.class, "orderStatus0", false, "ORDER_STATUS0");
        public final static Property OrderStatus1 = new Property(8, int.class, "orderStatus1", false, "ORDER_STATUS1");
        public final static Property OrderStatus2 = new Property(9, int.class, "orderStatus2", false, "ORDER_STATUS2");
        public final static Property Error = new Property(10, Boolean.class, "error", false, "ERROR");
        public final static Property Message = new Property(11, String.class, "message", false, "MESSAGE");
    }

    private DaoSession daoSession;


    public CabinetModelDao(DaoConfig config) {
        super(config);
    }
    
    public CabinetModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CABINET_MODEL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"BALANCE_ID\" INTEGER NOT NULL ," + // 1: balanceID
                "\"DATE_OPERATION\" INTEGER NOT NULL ," + // 2: dateOperation
                "\"BALANCE\" REAL NOT NULL ," + // 3: balance
                "\"CART_ID\" INTEGER NOT NULL ," + // 4: cartID
                "\"TOVAR_COUNT\" INTEGER NOT NULL ," + // 5: tovarCount
                "\"CART_SUMMA\" REAL NOT NULL ," + // 6: cartSumma
                "\"ORDER_STATUS0\" INTEGER NOT NULL ," + // 7: orderStatus0
                "\"ORDER_STATUS1\" INTEGER NOT NULL ," + // 8: orderStatus1
                "\"ORDER_STATUS2\" INTEGER NOT NULL ," + // 9: orderStatus2
                "\"ERROR\" INTEGER," + // 10: error
                "\"MESSAGE\" TEXT);"); // 11: message
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CABINET_MODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CabinetModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getBalanceID());
        stmt.bindLong(3, entity.getDateOperation());
        stmt.bindDouble(4, entity.getBalance());
        stmt.bindLong(5, entity.getCartID());
        stmt.bindLong(6, entity.getTovarCount());
        stmt.bindDouble(7, entity.getCartSumma());
        stmt.bindLong(8, entity.getOrderStatus0());
        stmt.bindLong(9, entity.getOrderStatus1());
        stmt.bindLong(10, entity.getOrderStatus2());
 
        Boolean error = entity.getError();
        if (error != null) {
            stmt.bindLong(11, error ? 1L: 0L);
        }
 
        String message = entity.getMessage();
        if (message != null) {
            stmt.bindString(12, message);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CabinetModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getBalanceID());
        stmt.bindLong(3, entity.getDateOperation());
        stmt.bindDouble(4, entity.getBalance());
        stmt.bindLong(5, entity.getCartID());
        stmt.bindLong(6, entity.getTovarCount());
        stmt.bindDouble(7, entity.getCartSumma());
        stmt.bindLong(8, entity.getOrderStatus0());
        stmt.bindLong(9, entity.getOrderStatus1());
        stmt.bindLong(10, entity.getOrderStatus2());
 
        Boolean error = entity.getError();
        if (error != null) {
            stmt.bindLong(11, error ? 1L: 0L);
        }
 
        String message = entity.getMessage();
        if (message != null) {
            stmt.bindString(12, message);
        }
    }

    @Override
    protected final void attachEntity(CabinetModel entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CabinetModel readEntity(Cursor cursor, int offset) {
        CabinetModel entity = new CabinetModel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // balanceID
            cursor.getLong(offset + 2), // dateOperation
            cursor.getDouble(offset + 3), // balance
            cursor.getInt(offset + 4), // cartID
            cursor.getInt(offset + 5), // tovarCount
            cursor.getDouble(offset + 6), // cartSumma
            cursor.getInt(offset + 7), // orderStatus0
            cursor.getInt(offset + 8), // orderStatus1
            cursor.getInt(offset + 9), // orderStatus2
            cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0, // error
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11) // message
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CabinetModel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBalanceID(cursor.getInt(offset + 1));
        entity.setDateOperation(cursor.getLong(offset + 2));
        entity.setBalance(cursor.getDouble(offset + 3));
        entity.setCartID(cursor.getInt(offset + 4));
        entity.setTovarCount(cursor.getInt(offset + 5));
        entity.setCartSumma(cursor.getDouble(offset + 6));
        entity.setOrderStatus0(cursor.getInt(offset + 7));
        entity.setOrderStatus1(cursor.getInt(offset + 8));
        entity.setOrderStatus2(cursor.getInt(offset + 9));
        entity.setError(cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0);
        entity.setMessage(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CabinetModel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CabinetModel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CabinetModel entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
